### ISSUE TITLE
Can't try calenderkit

### ISSUE THREAD

**Issue by tanphamanhh** [richardtop/CalendarKit#230]
### Command

```
/usr/local/bin/pod try CalendarKit
```

### Report

* What did you do?
using terminal to run calenderkit with command above
* What did you expect to happen?
I can try CalenderKit
* What happened instead?
Error when try

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.1 (11A1027)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ de223eab84be5859f6c923fda85aa56b7c2f340c
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by richardtop** [comment]
Hi, it’s a known CocoaPods bug, try running ‘pod try Hero’, for example: you’ll get the same error.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by richardtop** [comment]
Closing, as it's issue not related to the CalendarKit
